### PR TITLE
GSOC 2007 code push

### PR DESCRIPTION
**Pull request by bararchy**

### CODE REVIEW

**Comment by sciencefyll** [comment]
Nice! Before I merge this can you add not needed files and folders to .gitignore for a clean up?

**Comment by bararchy** [comment]
@sciencefyll Sure, but I dont really know CSV and never used it, do you know which files I should ignore ?

**Comment by sciencefyll** [comment]
Theres +1k files so for now, just add ` BorlandC++Builder6.0` and `Borland Studio` folders to .gitignore

**Comment by bararchy** [comment]
@sciencefyll Sorry for taking so long, removed the files and added to gitignore

**Comment by bararchy** [comment]
Also, should we get rid of this: CodeGear RAD Studio ?

**Comment by bararchy** [comment]
Also it seems we can remove the CVS dir ?

**Comment by bararchy** [comment]
Just pinging again for goodluck :) 
@sciencefyll

**Comment by sciencefyll** [comment]
I'm a tad busy this week.
But if you see any files that can be removed, just do so. But you have tried to compile this and run the tests, correct?

**Comment by bararchy** [comment]
@sciencefyll Compilation works, so does specific branch tests, what I don't know how to test is compatibility  with the current API, as in making sure there aren't breaking changes from current code.

**Pull request merged**
